services:
  # BASE DE DATOS
  db:
    image: timescale/timescaledb:latest-pg16
    container_name: timescale_tfg
    restart: always
    environment:
      - POSTGRES_DB=tfg_embrace
      - POSTGRES_USER=ines
      - POSTGRES_PASSWORD=tfg_password
    ports:
      - "5433:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  # API FASTAPI
  api_v2:
    build: 
      context: .
      dockerfile: backend/Dockerfile
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_NAME=tfg_embrace
      - DB_USER=ines
      - DB_PASSWORD=tfg_password
      - DB_PORT=5432
    volumes:
      # Conectamos carpetas reales con el contenedor en tiempo real
      - ./backend:/app/backend
      - ./scripts:/app/scripts
      - ./data:/app/data